apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-streamlit
  template:
    metadata:
      labels:
        app: iris-streamlit
    spec:
      containers:
      - name: iris-streamlit
        image: mymbbcontainerregistry.azurecr.io/sachinpandit1729/iris
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: iris-streamlit-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8501
  selector:
    app: iris-streamlit